name: AndroidBuild

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

Mygit:
  build:
    runs-on: window-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
